### ISSUE TITLE
can't add images to RSS

### ISSUE THREAD

**Issue by aryeharmon** [mibe/FeedWriter#29]
There is no built in way to add images to the items

**Comment by mibe** [comment]
Yes, this is due to the fact that the [RSS specification](http://www.rssboard.org/rss-specification#hrelementsOfLtitemgt) does not support item specific images. But you can add inline images as HTML code in the item description, like this:
`$newItem->setDescription('<img src="http://example.com/image.jpg">');`

**Comment by aryeharmon** [comment]
Actually i found that there is a way to add it with the media method. Thanks
