### ISSUE TITLE
Example throws Internal Error 500 on use \FeedWriter\RSS2;

### ISSUE THREAD

**Issue by tomaszs** [mibe/FeedWriter#32]
When i put into a function those lines:

include '../addons/rss/Item.php';
    include '../addons/rss/Feed.php';
    include '../addons/rss/RSS2.php';
    
    date_default_timezone_set('UTC');
    
    use \FeedWriter\RSS2;

I have internal server Error 500. If i remove "use" it works fine. I have good version of PHP

**Comment by mibe** [comment]
Can you give a bit more information about your system? What PHP version are you using? Can you also check the error logfile of your webserver for PHP errors?

**Comment by tomaszs** [comment]
Hello, Thanks for answer. I have PHP Version 	5.3.29. I can not find any errors in error long, but it can also be that it was truncated or else

**Comment by mibe** [comment]
What happens when you remove the first backslash in the `use` line?

If the webserver's error log does not help, try setting PHP's configuration option [`error_log`](https://secure.php.net/manual/en/errorfunc.configuration.php#ini.error-log) in your php.ini file or via a .htaccess directive (if you are using Apache). That should save the error message to a file (which must be writeable by the webserver).

The output of `phpinfo()` would probably also help.

**Comment by tomaszs** [comment]
Thanks for suggestions. I've had a little time, so i implemented code myself. I will be back when i will have new project to use FeedWriter.

**Comment by mibe** [comment]
Bummer! I had no luck reproducing this behaviour on my 5.3.29 installation... :disappointed:
